config/routes.rb
Rails.application.routes.draw do
  resources :hotel_bookings
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'home/signup'
  
  get 'home/index'
  root to: 'home#index'
  get 'hotels/show_list'
  get 'profile/user'
  get 'bookings/show_bookings'
  get 'bookings/insert_booking'
  get 'bookings/booking_success'

  namespace :api do
    namespace :v1 do
      resources :hotels
    end  
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :hotel
end

app/models/hotel.rb
class Hotel < ApplicationRecord
    has_many :bookings
end

app/models/hotel_booking.rb
class HotelBooking < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
end

app/controllers/api/v1/hotels_controller.rb
class Api::V1::HotelsController < ApplicationController
    def index
        @hotels = Hotel.all
        render json: @hotels
    end
    
    def create
        @hotel = Hotel.new(params["name"])
        if @hotel.save
            render json: @hotel
        else
            render error: { error: "Not able to save" }, status: 400
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

         def configure_permitted_parameters
              devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:user_name, :email, :password)}

              devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:user_name, :email, :password, :current_password)}
         end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    def show_bookings
      @book = Booking.where(user_id: current_user.id)
    end
    
    def insert_booking
      @hotels = Hotel.all
    end
  
    def booking_success
    end

  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def signup
  end
end

app/controllers/hotel_bookings_controller.rb
class HotelBookingsController < ApplicationController
  before_action :set_hotel_booking, only: %i[ show edit update destroy ]

  # GET /hotel_bookings or /hotel_bookings.json
  def index
    @hotel_bookings = HotelBooking.all
  end

  # GET /hotel_bookings/1 or /hotel_bookings/1.json
  def show
  end

  # GET /hotel_bookings/new
  def new
    @hotel_booking = HotelBooking.new
  end

  # GET /hotel_bookings/1/edit
  def edit
  end

  # POST /hotel_bookings or /hotel_bookings.json
  def create
    @hotel_booking = HotelBooking.new(hotel_booking_params)

    respond_to do |format|
      if @hotel_booking.save
        format.html { redirect_to @hotel_booking, notice: "Hotel booking was successfully created." }
        format.json { render :show, status: :created, location: @hotel_booking }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hotel_booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotel_bookings/1 or /hotel_bookings/1.json
  def update
    respond_to do |format|
      if @hotel_booking.update(hotel_booking_params)
        format.html { redirect_to @hotel_booking, notice: "Hotel booking was successfully updated." }
        format.json { render :show, status: :ok, location: @hotel_booking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hotel_booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotel_bookings/1 or /hotel_bookings/1.json
  def destroy
    @hotel_booking.destroy
    respond_to do |format|
      format.html { redirect_to hotel_bookings_url, notice: "Hotel booking was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel_booking
      @hotel_booking = HotelBooking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hotel_booking_params
      params.require(:hotel_booking).permit(:name, :address, :phoneno)
    end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
    def show_list
        @hotels = Hotel.all
    end
end

app/controllers/profile_controller.rb
  class ProfileController < ApplicationController
    def user
      
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hotel_bookings_helper.rb
module HotelBookingsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/bookings/booking_success.html.erb
<p>Successfully booked</p>

app/views/bookings/delete.html.erb
<br>
<div class="alert alert-danger" role="alert">
    <h2>Bookings are deleted successfully</h2>
</div>

app/views/bookings/insert_booking.html.erb
<br>
<h3>Hotels List</h3>
<form method="get" action="/bookings/booking_success">
    <label for="hotels">Hotel Name</label>
        <select id="hotels" name="booked[hotel_name]" class="form-select">
            <option selected="selected" disabled="disabled" >Select the hotel</option>
            <% @hotels.each do |hotel| %>
            <option value="<%= hotel.hotel_name %>"><%= hotel.hotel_name %></option>
            <% end %>
        </select>
        

    <div class="col">
        <button type="submit"  class="btn btn-dark">Book</button>
    </div>
</form>

app/views/bookings/show_bookings.html.erb
<br>
<% if @book %>
  <div class="card mx-5">
  <h3 class="card-header bg-dark text-white mx-2">Hotel details</h3>
  <div class="card-body">
    <table class="table table-striped table-hover table-sm">
      <thead>
        <tr>
          <th>User Name</th>
          <th>Hotel Name</th>
          <th>Date</th>
          <th>Time</th>
          <th>No of guests</th>
        </tr>
      </thead>

      <tbody>
        <% @book.each do |b| %>
          <tr>
            <td><%= User.find_by(id: b.user_id).user_name %></td>
            <td><%= b.h_name %></td>
            <td><%= b.b_date %></td>
            <td><%= b.b_time %></td>
            <td><%= b.no_of_booking %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-4">
        <b>Press delete to delete your booking.</b>
      </div>
      <div class="col">
        <%= link_to "Delete all bookings", bookings_delete_path, method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
  </div>

<% else %>
  <div class="row row-content">
    <div class="col-4 offset-1">
      <h2> Please book a hotel first! </h2>
    </div>
    <div class="col">
      <a class="btn btn-dark " href="/bookings/booking_success" role="button">Book Here</a>
    </div>
  </div>
<% end %>

app/views/home/index.html.erb
<div class="container py-4" >
  <div class="pb-3 mb-4 border-bottom">
    <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
      <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img"><title>Bootstrap</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path></svg>
      <span class="fs-4">Assignment</span>
    </a>
  </div>
</div>

app/views/home/signup.html.erb
<h1>Hello</h1>
<p>This is Sign up page</p>
<%= link_to 'Sign up', home_signup_path %>
<%= link_to 'Home', home_index_path %>

app/views/hotel_bookings/_form.html.erb
<%= form_with(model: hotel_booking) do |form| %>
  <% if hotel_booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hotel_booking.errors.count, "error") %> prohibited this hotel_booking from being saved:</h2>

      <ul>
        <% hotel_booking.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :phoneno %>
    <%= form.number_field :phoneno %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/hotel_bookings/edit.html.erb
<h1>Editing Hotel Booking</h1>

<%= render 'form', hotel_booking: @hotel_booking %>

<%= link_to 'Show', @hotel_booking %> |
<%= link_to 'Back', hotel_bookings_path %>

app/views/hotel_bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-white">Hotel Bookings</h1>

<table class="table table-hover table-sm table-dark">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phoneno</th>
      
    </tr>
  </thead>

  <tbody>
    <% @hotel_bookings.each do |hotel_booking| %>
      <tr>
        <td><%= hotel_booking.name %></td>
        <td><%= hotel_booking.address %></td>
        <td><%= hotel_booking.phoneno %></td>
        <td><%= link_to 'Show', hotel_booking %></td>
        <td><%= link_to 'Edit', edit_hotel_booking_path(hotel_booking) %></td>
        <td><%= link_to 'Destroy', hotel_booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hotel Booking', new_hotel_booking_path %>

app/views/hotel_bookings/new.html.erb
<% if user_signed_in? %>
    <h1 class="text-brown">New Hotel Booking</h1>

    <%= render 'form', hotel_booking: @hotel_booking %>

    <%= link_to 'Back', hotel_bookings_path, class: "btn btn-primary" %>
<% else %>
    <h1>Please Sign in First</h1>
<% end %>

app/views/hotel_bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p class="text-white">
  <strong>Name:</strong>
  <%= @hotel_booking.name %>
</p>

<p class="text-white">
  <strong>Address:</strong>
  <%= @hotel_booking.address %>
  &emsp;
</p>

<p class="text-white">
  <strong>Phoneno:</strong>
  <%= @hotel_booking.phoneno %>
</p>


<%= link_to 'Edit', edit_hotel_booking_path(@hotel_booking), class: "btn btn-primary" %> |
<%= link_to 'Back', hotel_bookings_path, class: "btn btn-primary" %>

app/views/hotels/show_list.html.erb
<br>
<h3 class="text-white">Hotels List</h3>
<table class="table table-hover table-sm table-dark">
  <thead>
    <tr>
      <th>S.No.</th>
      <th>Hotel Name</th>
    </tr>
  </thead>

  <tbody>
    <% @hotels.each do |hotel| %>
      <tr>
        <td><%= hotel.id %></td>
        <td><%= hotel.hotel_name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Expand at lg</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample05">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/users/sign_in">Sign In</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/users/sign_up">Sign Up</a>
          </li>
          <li class="nav-item">
            <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/hotels/show_list">Show Hotels</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/hotel_bookings/new">Book a Hotel</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-md-0">
          <input class="form-control" type="text" placeholder="Search">
        </form>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assignment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', 'https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css' %>
    <script src="https://use.fontawesome.com/837bb55569.js"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      body{
        background-image: url("https://lonelyplanetwpnews.imgix.net/2017/10/34884794003_79b7caebee_k-e1509108009678.jpg");
        background-repeat: no-repeat;
        background-size: 1030px 550px;
      }
    </style>
  </head>

  <body>
  
    <%= render "layouts/header" %>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>